Repository bigchaindb/bigchaindb, pull requests merged in 2018-02, with the labels that each got.

#1993 Updated all refs to the IPDB Transaction Spec and its URL
  docs/root/source/assets.rst
  docs/root/source/permissions.rst
  docs/root/source/smart-contracts.rst
  docs/root/source/transaction-concepts.md
  docs/server/source/appendices/cryptography.rst
  docs/server/source/appendices/json-serialization.rst
  docs/server/source/data-models/asset-model.rst
  docs/server/source/data-models/conditions.rst
  docs/server/source/data-models/inputs-outputs.rst
  docs/server/source/data-models/transaction-model.rst
  docs/server/source/data-models/vote-model.rst
Labels: tendermint, topic: UX docs cmd api driver

#2033 Implement UTXO set backend
  bigchaindb/backend/localmongodb/query.py
  bigchaindb/backend/localmongodb/schema.py
  bigchaindb/backend/query.py
  tests/backend/localmongodb/conftest.py
  tests/backend/localmongodb/test_queries.py
  tests/backend/localmongodb/test_schema.py
  tests/conftest.py
  tests/utils.py
Labels: tendermint

#2048 Changed constructed/allowed transaction 'version' from '1.0' to '2.0'
  bigchaindb/common/schema/__init__.py
  bigchaindb/common/schema/transaction_create_v2.0.yaml
  bigchaindb/common/schema/transaction_transfer_v2.0.yaml
  bigchaindb/common/schema/transaction_v2.0.yaml
  bigchaindb/common/transaction.py
  docs/server/source/data-models/transaction-model.rst
  tests/validation/test_transaction_structure.py
Labels: tendermint, tx model

#2061 Remove location header from post txn response
  bigchaindb/web/views/transactions.py
  docs/server/generate_http_server_api_documentation.py
  docs/server/source/http-client-server-api.rst
Labels: tendermint

#2062 Remove the HTTP API docs for the /statuses & /votes endpoints
  docs/server/generate_http_server_api_documentation.py
  docs/server/source/http-client-server-api.rst
Labels: tendermint

#2056 Problem: Transaction CLI Tool deprecated but linked from some docs
  docs/root/source/index.rst
  docs/server/source/drivers-clients/index.rst
Labels: tendermint

#2069 Remove all code for all /statuses endpoints
  bigchaindb/web/routes.py
  bigchaindb/web/views/info.py
  bigchaindb/web/views/statuses.py
  tests/web/test_info.py
  tests/web/test_statuses.py
  tests/web/test_transactions.py
Labels: tendermint

#2065 Updated (almost) all docs regarding "votes" once Tendermint integrated
  docs/root/source/decentralized.md
  docs/root/source/immutable.md
  docs/server/source/appendices/index.rst
  docs/server/source/appendices/vote-yaml.rst
  docs/server/source/data-models/index.rst
  docs/server/source/data-models/vote-model.rst
  docs/server/source/events/websocket-event-stream-api.rst
  docs/server/source/http-client-server-api.rst
Labels: tendermint

#2063 Some edits to common/schema/README.md
  bigchaindb/common/schema/README.md
Labels: tendermint

#2045 Crash recovery mechanism
  bigchaindb/backend/localmongodb/query.py
  bigchaindb/backend/query.py
  bigchaindb/commands/bigchaindb.py
  bigchaindb/tendermint/lib.py
  compose/travis/Dockerfile
  docker-compose.travis.yml
  tests/backend/localmongodb/test_queries.py
  tests/commands/test_commands.py
  tests/conftest.py
  tmdata/genesis.json
  tmdata/priv_validator.json
Labels: tendermint

#1992 Template for BigchainDB + Tendermint Kubernetes Deployment
  docs/server/requirements.txt
  docs/server/source/appendices/firewall-notes.md
  docs/server/source/conf.py
  docs/server/source/data-models/block-model.rst
  docs/server/source/data-models/transaction-model.rst
  docs/server/source/events/websocket-event-stream-api.rst
  docs/server/source/http-client-server-api.rst
  docs/server/source/production-deployment-template/add-node-on-kubernetes.rst
  docs/server/source/production-deployment-template/architecture.rst
  docs/server/source/production-deployment-template/bigchaindb-network-on-kubernetes.rst
  docs/server/source/production-deployment-template/ca-installation.rst
  docs/server/source/production-deployment-template/client-tls-certificate.rst
  docs/server/source/production-deployment-template/cloud-manager.rst
  docs/server/source/production-deployment-template/easy-rsa.rst
  docs/server/source/production-deployment-template/index.rst
  docs/server/source/production-deployment-template/node-config-map-and-secrets.rst
  docs/server/source/production-deployment-template/node-on-kubernetes.rst
  docs/server/source/production-deployment-template/restore-from-mongodb-cloud-manager.rst
  docs/server/source/production-deployment-template/revoke-tls-certificate.rst
  docs/server/source/production-deployment-template/server-tls-certificate.rst
  docs/server/source/production-deployment-template/tectonic-azure.rst
  docs/server/source/production-deployment-template/template-kubernetes-azure.rst
  docs/server/source/production-deployment-template/troubleshoot.rst
  docs/server/source/production-deployment-template/upgrade-on-kubernetes.rst
  docs/server/source/production-deployment-template/workflow.rst
  setup.py
Labels: k8s-deployment, tendermint

#2068 Remove all refs/links to whitepaper in tendermint branch
  README.md
  bigchaindb/README.md
Labels: tendermint

#2086 Make votes endpoint return 404 and a helpful message
  bigchaindb/web/views/votes.py
  tests/web/test_votes.py
Labels: tendermint, topic: UX docs cmd api driver

#2091 Rollback crash recovery mechanism
  bigchaindb/commands/bigchaindb.py
  tests/commands/test_commands.py
Labels: tendermint

#1976 Proposal: Migrate cli for Tendermint
  proposals/migrate-cli.md
Labels: proposal, tendermint
